### ISSUE TITLE
raster image not updated after matching is just enabled 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#1571]
After we have images matched, switching to different images should show similar source features in the following example (matching CO, 13CO and C18O line cubes). 

@veggiesaurus do you think this is due to tile cache PR?

https://user-images.githubusercontent.com/20819712/125720351-3d7d395d-3ebb-4fe3-8db2-8ab8ba5abc8e.mov

**Comment by veggiesaurus** [comment]
Hmm, ok I see the issue. 

What is the expected behaviour though? If you change images, we'll then have to fetch the new channel's images from the server, so there may be a situation where the old images are displayed initially and the new ones are then received

**Comment by kswang1029** [comment]
> Hmm, ok I see the issue.
> 
> What is the expected behaviour though? If you change images, we'll then have to fetch the new channel's images from the server, so there may be a situation where the old images are displayed initially and the new ones are then received

That should be fine for the first time. Once it is cached switching to different images back and forth with fixed FOV should be smooth(?).

**Comment by veggiesaurus** [comment]
> That’s should be fine for the first time. Once it is cached switching to different images back and forth with fixed FOV should be smooth(?).

Yes :+1:

**Comment by veggiesaurus** [comment]
@kswang1029 can you see if this is also fixed by #1596? I think it was my idiotic typo (`=== undefined` instead of `!== undefined` :facepalm: )

**Comment by kswang1029** [comment]
> @kswang1029 can you see if this is also fixed by #1596? I think it was my idiotic typo (`=== undefined` instead of `!== undefined` 🤦 )

Nope, the issue is still there with #1596. When grid mode is on, I see all panels get updated when switching channel but when the grid mode is off (single panel mode), the issue happens.

**Comment by kswang1029** [comment]
@veggiesaurus I suggest we still align the tool bar to the right as if we align to the left, it will block the beam element overlay. 

<img width="1782" alt="Screen Shot 2021-08-09 at 10 05 00 AM" src="https://user-images.githubusercontent.com/20819712/128653768-eb75abf0-f3ca-46b2-8c44-47b5f984bfa1.png">
